### ISSUE TITLE
No option to switch between Scry and Teleport Modes

### ISSUE THREAD

**Issue by Cyborger1** [Antipixel/nexus-map#1]
The UI has no option to switch between Teleport/Scry. If Scry is selected before enabling the plugin, there is no way to change it back to Teleport. Attempting to teleport will Scry instead, requiring the user to turn the plugin off and change it there.

**Comment by Antipixel** [comment]
The new version now includes a toggle option in the top-left of the Nexus menu that will let you access the Teleport/Scry, which should solve this problem. The menu option text will also now reflect the active mode.
![image](https://user-images.githubusercontent.com/8239026/104707007-cc38a380-5756-11eb-8abf-8a65b4ae155b.png)
