### ISSUE TITLE
Incompatible with better teleport menu plugin.

### ISSUE THREAD

**Issue by AustinGarrettR** [Antipixel/nexus-map#10]
There is another plugin on the plugin hub, called Better teleport menu.
The plugin will change the ancient teleport names to normal names. (Ex. Annakarl changes to Demonic Ruins).

When the plugin is active, the nexus map plugin greys out the teleports because it thinks they aren't unlocked.
It's not required this plugin be compatible, but it would be nice! Thanks.

**Comment by groteworld** [comment]
Can close this issue with closing of #11

**Comment by Cyborger1** [comment]
Closing as this should no longer be an issue as of #24.

Please reopen if there's an issue.
