### ISSUE TITLE
Is it possible to outline teleports?

### ISSUE THREAD

**Issue by mastersuleman** [Antipixel/nexus-map#13]
Is it possible to put a coloured outline around teleports?
The teleports tend to blend into the beautiful artwork and make it difficult to see. 

I do love this nexus map but I'm having trouble with seeing teleports sometimes.

**Comment by Antipixel** [comment]
For the latest version I've added a few options to aid in visibility:

**Black Outline**
Helps the teleport icon to stand out a bit more
![black_outline](https://github.com/Antipixel/nexus-map/assets/8239026/854e9182-90cf-4356-a792-640377b68c30)

**White Outline**
Gives even more contrast against the map
![white_outline](https://github.com/Antipixel/nexus-map/assets/8239026/45d62963-1312-4a52-a43b-9651631d777b)

**Pulsing Fade Animation**
Can be used in conjunction with the icon outline options
![Nexus_Blink](https://github.com/Antipixel/nexus-map/assets/8239026/ba2d519c-bcff-49d6-af0f-f08ef4e35109)

These options can now be enabled in the plugin config
