### ISSUE TITLE
Carrallanger teleport grayed out

### ISSUE THREAD

**Issue by jimminylubbox** [Antipixel/nexus-map#14]
With the desert treasure 2 update, carrallanger teleport to the wilderness has been grayed out despite having it unlocked
![image](https://github.com/Antipixel/nexus-map/assets/131806474/dc7fa5bb-1b6b-4ac2-8d46-d1fa0752840a)
![image](https://github.com/Antipixel/nexus-map/assets/131806474/fc2c07c3-ea87-4e7b-92b0-b340e8cf8159)

**Comment by Antipixel** [comment]
Thanks for letting me know, will be sorted shortly.
