### ISSUE TITLE
Can a teleport to Civitas illa Fortis be added to the map by a developer (or the user)?

### ISSUE THREAD

**Issue by RuneLiteEnjoyer** [Antipixel/nexus-map#20]
Title. I wouldn't even call myself a novice programmer so I'm unsure of how'd I'd be able to do it myself, so thought I would ask here. Really love this plugin and hope it continues to get updates when (and if) more teleports get added to the nexus.

Thanks :)

**Comment by groteworld** [comment]
Duplicate of #17

Closes with #18

**Comment by Cyborger1** [comment]
Fixed with version 1.0.4
