### ISSUE TITLE
digsite shows on map but can't click

### ISSUE THREAD

**Issue by lucashw97** [Antipixel/nexus-map#21]
the digsite teleport is greyed out on the map but if i go to the menu i can teleport

**Comment by iUndef** [comment]
Also having this issue. After some troubleshooting, at least on my end, it seems to be a conflict between this plugin and the 'Normal Ancient Teleports' plugin. Seems that somewhere in the process of the names of the Ancient teleports being renamed, they break with the map. Disabling either of the plugins fixes the issue, but with the obvious downside that you're now missing the functionality of the now-disabled plugin.

**Comment by Cyborger1** [comment]
Closing as this should no longer be an issue as of #24.

Please reopen if there's an issue.
