### ISSUE TITLE
Nexus Menu Map outdated..

### ISSUE THREAD

**Issue by ADHDMAN** [Antipixel/nexus-map#22]
![Screenshot 2024-11-02 224115](https://github.com/user-attachments/assets/e12d9753-448c-43d3-b2a0-51db127c655d)

![Screenshot 2024-11-02 224251](https://github.com/user-attachments/assets/e461deb5-f41b-43bf-aef0-fbae1ec3d0ca)
No Varlamore teleport aka Civitas illa Fortis 
So have to not show map to use or use the Civitas illa Fortis tabs...

**Comment by Cyborger1** [comment]
Will be resolved when https://github.com/Antipixel/nexus-map/pull/18 is PR'ed to the hub

**Comment by Cyborger1** [comment]
Fixed with 1.0.4
