### ISSUE TITLE
Shortcut Keys are not functional

### ISSUE THREAD

**Issue by BlueVasos** [Antipixel/nexus-map#26]
Seen the update to the map (Awesome job btw) I am no longer able to use shortcut keys unless i turn off the map by uncheckmarking to go to listview. Keep up the good work lovin it!

**Comment by Cyborger1** [comment]
Confirmed, gonna take a look

**Comment by Cyborger1** [comment]
Got a fix up now, that was my bad. As I was reworking the plugin, I had some assumptions about the inner workings of OSRS's interface systems that turned out to be incorrect, and I forgot to check that keybinds still worked when in map mode... Sorry!

**Comment by BlueVasos** [comment]
Just got on and confirmed the fix! sick man keep up the good work im enjoying the hell out of it.

**Comment by Cyborger1** [comment]
Good to know! Closing now, have a good day 👍
