### ISSUE TITLE
Kharyll Teleport Not Showing

### ISSUE THREAD

**Issue by phillyftw** [Antipixel/nexus-map#5]
Kharyll telly isnt showing as being available on the map but if i go back to list i can see it.

**Comment by phillyftw** [comment]
looks as if all ancient teleports not showing on the map even though they are in the nexus.

**Comment by Antipixel** [comment]
Are you also running the "Better Teleport Menu" plugin? There appears to be a compatibility issue that causes similar problems

**Comment by phillyftw** [comment]
Good call that fixed it. Thanks
