### ISSUE TITLE
Showing blank teleports even if unlocked

### ISSUE THREAD

**Issue by Zachpoole96** [Antipixel/nexus-map#9]
These spells are blanked out as if I don't have them unlocked, but I do and they're active on the vanilla menu.
Ape Atoll standard spellbook
Canifis Ancients spellbook
Digsite Ancients spellbook

**Comment by Antipixel** [comment]
I've heard this come up a few times before, it appears to be a compatibility issue with the "Better Teleport Menu" plugin.

Try switching off the "Alternate names" option in Better Teleport Menu's configuration.

**Comment by groteworld** [comment]
Can close this issue with closing of #11

**Comment by Cyborger1** [comment]
Closing as this should no longer be an issue as of #24.

Please reopen if there's an issue.
